#!/bin/sh

repo=$(readlink -f $1)
tmpfile=$(mktemp -t planXXXXXX)

trap "rm -f $tmpfile" EXIT

cat $2 > $tmpfile

cd "$repo" || exit 1
export WH_PLAN=$tmpfile
git filter-branch -f --tree-filter '
when=$(awk -vcid=$GIT_COMMIT "\$1 == cid {print \$2}" $WH_PLAN)
[ "$when" ] && export GIT_AUTHOR_DATE="$when" GIT_COMMITTER_DATE="$when"
' HEAD
